CREATE TABLE "players" (
	"gid" INTEGER PRIMARY KEY,
	"name" TEXT NOT NULL UNIQUE,
	"password" TEXT NOT NULL,
	"salt" TEXT NOT NULL,
	"perm_level" INTEGER NOT NULL DEFAULT 0,
	"money" INTEGER NOT NULL DEFAULT 0,
	"kills" INTEGER NOT NULL DEFAULT 0,
	"deaths" INTEGER NOT NULL DEFAULT 0,
	"skin_id" INTEGER DEFAULT NULL,
	"msp_x" REAL DEFAULT NULL,
	"msp_y" REAL DEFAULT NULL,
	"msp_z" REAL DEFAULT NULL,
	"msp_ang" REAL DEFAULT NULL,
	"msp_int" REAL DEFAULT NULL
);
